### ISSUE TITLE
$ENV{HOME}/.trunner

### ISSUE THREAD

**Issue by aanoaa** [JEEN/TRunner#1]
`home/.trunner/app.psgi`
`home/.trunner/config.yml`

를 install 할때 맨들어서 설정 및 실행 psgi 파일을 각각 install 한 개인이 둬서 쓸 수 있도록 하는 것이..?

```
wtf 아직 뭘 어케해야겠다를 모르겠음. 그냥 그렇게 해야되지 않나 싶어서..
```

**Comment by JEEN** [comment]
긁네요. 화이팅

**Comment by aanoaa** [comment]
`/home/user/.trunner` 에 smolder 에 대한 설정이 들어가고요.
TRunner 의 `bin/app.psgi`, `public/`, `views/`, `config.yml`, `selenium.yml` 은 공용 디렉토리에 설치됩니다.
